modLoader="javafml"
loaderVersion="[36,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/xhanhh/ZycsDream-forge/issues"
[[mods]]
modId="zycsdream"
version="0.1.3beta2a"
displayName="ZYC's Dream"
displayURL="https://github.com/xhanhh/ZycsDream-forge"
logoFile="zyc.png"
credits="SCPC Studio"
authors="xhanhh"
description='''
张煜晨的天堂

此版本为测试版0.1.3beta2a
如有任何问题请提交Issue

本模组使用的肖像和名称已经过本人同意。
'''
[[dependencies.zycsdream]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.zycsdream]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
